### ISSUE TITLE
How to deploy it into app ?? 

### ISSUE THREAD

**Issue by Aniket-op** [Schlaubischlump/KivyFaceRecognition#1]

**Comment by Schlaubischlump** [comment]
This is a question for the kivy project. They provide templates to deploy a kivy app on iOS / Android / macOS / Linux and Windows.

**Comment by Aniket-op** [comment]
> This is a question for the kivy project. They provide templates to deploy a kivy app on iOS / Android / macOS / Linux and Windows.

Actually, I am building a face recognition attendance system app!  I  have managed to get the names of corresponding persons under the person's face on camera.  when I converted it into an app, it crashed 🥲(it pops up the loading screen and gets terminated). I think it is because of libraries like 'os' I have used! By any chance can you help me? from any medium like zoom meeting or I'll share Vs code share link.

**Comment by Schlaubischlump** [comment]
- Which platform are you targeting ? iOS, macOS, Android, Windows ? 
- Which app do you use to bundle your application? PyInstaller, something else ? 
- What is the error message that is produced, when you try to start the bundled app ?

**Comment by Aniket-op** [comment]
> - Which platform are you targeting ? iOS, macOS, Android, Windows ? 
> - Which app do you use to bundle your application? PyInstaller, something else ? 
> - What is the error message that is produced, when you try to start the bundled app ? 

- I'm targeting only Android for the time being

- I have used  buildozer .
I referred to it from the video below 
link:- https://youtu.be/XqWLaMtDCyk

- when i try to open it on Android it pop's up loading screen with kivy logo for 1-2 seconds than it shutdown

(Thx for the response. I really appreciate that 😊)

can we further communication on discord or telegram ? or here only?

**Comment by Schlaubischlump** [comment]
Telegram should work as well. You should find me under my github name.

You need a more precise error log. The app crashing is not helpful to find out what is wrong with your app. I do not have any experience with Android development, so I'm not sure that I'm the right person to help you with that. According to the buildozer github page you should run `buildozer android debug deploy run` to deploy and run your app. If you do it that way, the terminal should output some kind of error message.

**Comment by Hhllo** [comment]
@Schlaubischlump Hi,I'm faceing the same issue, do you fix it? Would you like to share your method and help me?

**Comment by Schlaubischlump** [comment]
Hi @Hhllo,

@Aniket-op never contacted me. I don't know if he was able to bundle it inside an app. 

There should be nothing to fix on my end. This is a question of: How do I use the kivy toolchain? And this has nothing to do with this project.

**Comment by Hhllo** [comment]
亲，我会第一时间阅读你的邮件，并回复你

**Comment by Aniket-op** [comment]
> Hi @Hhllo,
> 
> @Aniket-op never contacted me. I don't know if he was able to bundle it inside an app. 
> 
> There should be nothing to fix on my end. This is a question of: How do I use the kivy toolchain? And this has nothing to do with this project. 


Actually I had shifted to the Non code platform i.e Thunkable for building that App because of the shortage of time. 

That's why I never contacted,
My bad 😅
